// Mocks generated by Mockito 5.2.0 from annotations
// in microblog/test/features/signup/signup_controller_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i7;

import 'package:dartz/dartz.dart' as _i3;
import 'package:flutter/material.dart' as _i5;
import 'package:get/get.dart' as _i4;
import 'package:microblog/core/router/router.dart' as _i11;
import 'package:microblog/features/feed/data/feed_parameters.dart' as _i14;
import 'package:microblog/features/home/home_parameters.dart' as _i12;
import 'package:microblog/features/news/data/news_parameters.dart' as _i15;
import 'package:microblog/features/post/data/post_parameters.dart' as _i13;
import 'package:microblog/features/signup/data/signup_entity.dart' as _i10;
import 'package:microblog/features/signup/data/signup_response.dart' as _i9;
import 'package:microblog/features/signup/exceptions/signup_execute_exception.dart'
    as _i8;
import 'package:microblog/features/signup/signup_execute_use_case.dart' as _i6;
import 'package:microblog/features/signup/signup_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeISignupRepository_0 extends _i1.Fake
    implements _i2.ISignupRepository {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

class _FakeSnackbarController_2 extends _i1.Fake
    implements _i4.SnackbarController {}

class _FakeGlobalKey_3<T extends _i5.State<_i5.StatefulWidget>> extends _i1.Fake
    implements _i5.GlobalKey<T> {}

class _FakeGetSnackBar_4 extends _i1.Fake implements _i4.GetSnackBar {
  @override
  String toString({_i5.DiagnosticLevel? minLevel = _i5.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [SignupExecuteUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignupExecuteUseCase extends _i1.Mock
    implements _i6.SignupExecuteUseCase {
  MockSignupExecuteUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ISignupRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeISignupRepository_0()) as _i2.ISignupRepository);
  @override
  _i7.Future<_i3.Either<_i8.SignupExecuteException, _i9.SignupResponse>> call(
          {_i10.SignupEntity? data}) =>
      (super.noSuchMethod(Invocation.method(#call, [], {#data: data}),
          returnValue:
              Future<_i3.Either<_i8.SignupExecuteException, _i9.SignupResponse>>.value(
                  _FakeEither_1<_i8.SignupExecuteException,
                      _i9.SignupResponse>())) as _i7
          .Future<_i3.Either<_i8.SignupExecuteException, _i9.SignupResponse>>);
}

/// A class which mocks [IRouter].
///
/// See the documentation for Mockito's code generation for more information.
class MockIRouter extends _i1.Mock implements _i11.IRouter {
  MockIRouter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<TReturnType> startSignupPage<TReturnType>({bool? off = false}) =>
      (super.noSuchMethod(Invocation.method(#startSignupPage, [], {#off: off}),
              returnValue: Future<TReturnType>.value(null))
          as _i7.Future<TReturnType>);
  @override
  _i7.Future<TReturnType> startHomePage<TReturnType>(
          {bool? off = false, _i12.HomeParameters? parameters}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #startHomePage, [], {#off: off, #parameters: parameters}),
              returnValue: Future<TReturnType>.value(null))
          as _i7.Future<TReturnType>);
  @override
  _i7.Future<TReturnType> startLoginPage<TReturnType>({bool? off = false}) =>
      (super.noSuchMethod(Invocation.method(#startLoginPage, [], {#off: off}),
              returnValue: Future<TReturnType>.value(null))
          as _i7.Future<TReturnType>);
  @override
  _i7.Future<TReturnType> startPostPage<TReturnType>(
          {bool? off = false, _i13.PostParameters? parameters}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #startPostPage, [], {#off: off, #parameters: parameters}),
              returnValue: Future<TReturnType>.value(null))
          as _i7.Future<TReturnType>);
  @override
  _i7.Future<TReturnType> startFeed<TReturnType>(
          {bool? off = false, _i14.FeedParameters? parameters}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #startFeed, [], {#off: off, #parameters: parameters}),
              returnValue: Future<TReturnType>.value(null))
          as _i7.Future<TReturnType>);
  @override
  _i7.Future<TReturnType> startNews<TReturnType>(
          {bool? off = false, _i15.NewsParameters? parameters}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #startNews, [], {#off: off, #parameters: parameters}),
              returnValue: Future<TReturnType>.value(null))
          as _i7.Future<TReturnType>);
  @override
  _i7.Future<void> goBack<TReturnType>(
          {TReturnType? result,
          bool? closeOverlays = false,
          bool? canPop = true,
          int? id}) =>
      (super.noSuchMethod(
          Invocation.method(#goBack, [], {
            #result: result,
            #closeOverlays: closeOverlays,
            #canPop: canPop,
            #id: id
          }),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  _i4.SnackbarController showSnackbarSuccess({String? message}) =>
      (super.noSuchMethod(
          Invocation.method(#showSnackbarSuccess, [], {#message: message}),
          returnValue: _FakeSnackbarController_2()) as _i4.SnackbarController);
  @override
  _i4.SnackbarController showSnackbarError({String? message}) =>
      (super.noSuchMethod(
          Invocation.method(#showSnackbarError, [], {#message: message}),
          returnValue: _FakeSnackbarController_2()) as _i4.SnackbarController);
}

/// A class which mocks [SnackbarController].
///
/// See the documentation for Mockito's code generation for more information.
class MockSnackbarController extends _i1.Mock
    implements _i4.SnackbarController {
  MockSnackbarController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.GlobalKey<_i4.GetSnackBarState> get key =>
      (super.noSuchMethod(Invocation.getter(#key),
              returnValue: _FakeGlobalKey_3<_i4.GetSnackBarState>())
          as _i5.GlobalKey<_i4.GetSnackBarState>);
  @override
  _i4.GetSnackBar get snackbar =>
      (super.noSuchMethod(Invocation.getter(#snackbar),
          returnValue: _FakeGetSnackBar_4()) as _i4.GetSnackBar);
  @override
  _i7.Future<void> get future => (super.noSuchMethod(Invocation.getter(#future),
      returnValue: Future<void>.value()) as _i7.Future<void>);
  @override
  _i7.Future<void> close({bool? withAnimations = true}) => (super.noSuchMethod(
      Invocation.method(#close, [], {#withAnimations: withAnimations}),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  _i7.Future<void> show() => (super.noSuchMethod(Invocation.method(#show, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
}
